# Generated by Django 3.2.15 on 2023-01-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.IntegerField(),
        ),
    ]
