# Generated by Django 4.2 on 2023-04-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20230125_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='club_name',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='club_type',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
