# Generated by Django 4.2 on 2023-04-26 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_user_club_name_alter_user_club_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='club_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='club_type',
        ),
    ]
