# Generated by Django 4.2 on 2023-04-26 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_remove_user_account_type_remove_user_club_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email2',
            field=models.TextField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
