# Generated by Django 4.0 on 2023-05-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_emailverify'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('sns1_name', models.TextField(blank=True, max_length=100, null=True)),
                ('sns2_name', models.TextField(blank=True, max_length=100, null=True)),
                ('sns1_link', models.TextField(blank=True, max_length=100, null=True)),
                ('sns2_link', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
