# Generated by Django 4.0 on 2023-05-09 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_clubinfo_club_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='club_category',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
