# Generated by Django 4.0 on 2023-05-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_clubinfo_club_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubinfo',
            name='club_category',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='club_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
