# Generated by Django 4.0 on 2023-06-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_alter_clubinfo_club_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='image_01',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='clubinfo',
            name='image_02',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='clubinfo',
            name='image_03',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='clubinfo',
            name='image_04',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='clubinfo',
            name='intro_01',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='clubinfo',
            name='intro_02',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='clubinfo',
            name='leader',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clubinfo',
            name='room',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='clubinfo',
            name='year',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
