# Generated by Django 4.0 on 2023-04-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=32)),
                ('date', models.CharField(max_length=32)),
                ('time', models.CharField(max_length=32)),
                ('user_id', models.CharField(max_length=32)),
                ('user_name', models.CharField(max_length=100)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
