# Generated by Django 3.2.19 on 2023-11-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_reserve_room_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('start_day', models.IntegerField(default=0)),
                ('days', models.IntegerField(default=31)),
            ],
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='time',
        ),
        migrations.AddField(
            model_name='reserve',
            name='reserve_col',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reserve',
            name='reserve_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reserve',
            name='reserve_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reserve',
            name='user_tel',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='user_id',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
