# Generated by Django 4.0 on 2023-12-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20231129_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='create',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
