# Generated by Django 4.0 on 2023-12-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_create_end_date_alter_create_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='create',
            name='month',
            field=models.IntegerField(default=1),
        ),
    ]
