# Generated by Django 4.0 on 2023-12-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_create_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='create',
            name='row',
            field=models.IntegerField(default=5),
        ),
    ]
