# Generated by Django 4.0 on 2023-12-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_create_row'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=32)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('user_tel', models.CharField(default='', max_length=100)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
                ('reserve_time', models.DateTimeField()),
            ],
        ),
    ]
