# Generated by Django 4.0 on 2023-12-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_reserve_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve_new_search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_date', models.DateTimeField(default='2000-01-01')),
            ],
        ),
        migrations.AddField(
            model_name='reserve_new',
            name='reserve_date',
            field=models.DateTimeField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='reserve_new',
            name='user_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='reserve_new',
            name='reserve_time',
            field=models.CharField(default='', max_length=32),
        ),
    ]
