# Generated by Django 4.0 on 2023-12-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_reserve_new_search_reserve_new_reserve_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve_new',
            name='reserve_time',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='reserve_new',
            name='user_email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reserve_new',
            name='user_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='reserve_new',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reserve_new',
            name='user_tel',
            field=models.CharField(max_length=100),
        ),
    ]
