# Generated by Django 4.0 on 2023-12-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve_new',
            name='room',
            field=models.CharField(default='', max_length=100),
        ),
    ]
