# Generated by Django 4.0 on 2023-12-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_reserve_new_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
