# Generated by Django 4.0 on 2024-01-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_room_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve_new',
            name='reserve_desc_1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='reserve_new',
            name='reserve_desc_2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='reserve_new',
            name='reserve_desc_3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='reserve_new',
            name='reserve_num',
            field=models.CharField(default='', max_length=50),
        ),
    ]
