# Generated by Django 4.0 on 2024-01-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_reserve_new_reserve_desc_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Create',
        ),
        migrations.DeleteModel(
            name='Reserve',
        ),
        migrations.DeleteModel(
            name='Reserve_new_search',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
