# Generated by Django 3.2.19 on 2023-12-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('club', models.TextField(max_length=100)),
                ('phone_number', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('space', models.TextField(max_length=300)),
                ('date', models.TextField(max_length=300)),
                ('description', models.TextField(max_length=300)),
                ('people', models.TextField(max_length=100)),
                ('dy', models.TextField(default='', max_length=100)),
                ('stu', models.TextField(max_length=100)),
                ('checksum', models.TextField(max_length=10)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
