# Generated by Django 4.0 on 2023-12-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_reserve_file1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='reserve',
            name='stu',
            field=models.TextField(default='', max_length=100),
        ),
    ]
