# Generated by Django 4.0 on 2023-12-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0004_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
