# Generated by Django 4.0 on 2023-12-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_reset',
            field=models.BooleanField(default=False),
        ),
    ]
