# Generated by Django 4.0 on 2023-12-21 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_class'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='AddClass',
        ),
    ]
