# Generated by Django 4.0 on 2023-12-22 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_emailall'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailall',
            name='email2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
