# Generated by Django 4.0 on 2023-12-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_emailall_email2'),
    ]

    operations = [
        migrations.AddField(
            model_name='addclass',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
