# Generated by Django 4.0 on 2024-01-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_addclass_confirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_start', models.TextField(max_length=100)),
                ('club_end', models.TextField(max_length=100)),
                ('stu_start', models.TextField(max_length=100)),
                ('stu_end', models.TextField(max_length=100)),
            ],
        ),
    ]
